CREATE TABLE agencies
(
    agency_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency    TEXT NOT NULL,
    city      TEXT,
    state     TEXT,
    status    TEXT,
    ntd_id    INTEGER UNIQUE
);

INSERT INTO agencies (agency, city, state, status, ntd_id)
SELECT DISTINCT ON (m."NTD ID") m."Agency"          AS agency,
                                m."HQ City"         AS city,
                                m."HQ State"        AS state,
                                m."Status"          AS status,
                                m."NTD ID"::integer AS ntd_id
FROM public_transit_master m
WHERE m."NTD ID" IS NOT NULL
ORDER BY m."NTD ID",
         CASE WHEN m."Status" ILIKE 'Active%' THEN 0 ELSE 1 END,
         m."Agency";
