CREATE TABLE org_types
(
    org_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_type    TEXT NOT NULL UNIQUE
);

INSERT INTO org_types (org_type)
SELECT DISTINCT "Organization Type"
FROM public_transit_master
WHERE "Organization Type" IS NOT NULL
ON CONFLICT (org_type) DO NOTHING;

ALTER TABLE agencies
    ADD COLUMN IF NOT EXISTS org_type_id INT;

WITH raw_map AS (SELECT m."NTD ID"::integer                                    AS ntd_id,
                        t.org_type_id,
                        COUNT(*) OVER (PARTITION BY m."NTD ID", t.org_type_id) AS freq
                 FROM public_transit_master m
                          JOIN org_types t
                               ON t.org_type = m."Organization Type"
                 WHERE m."NTD ID" IS NOT NULL),
     choice AS (
         -- pick the most frequent org_type per NTD ID (tie-breaker left as frequency only)
         SELECT DISTINCT ON (ntd_id) ntd_id,
                                     org_type_id
         FROM raw_map
         ORDER BY ntd_id, freq DESC)
UPDATE agencies a
SET org_type_id = c.org_type_id
FROM choice c
WHERE a.ntd_id = c.ntd_id;

ALTER TABLE agencies
    ADD CONSTRAINT agencies_org_type_id_fkey
        FOREIGN KEY (org_type_id) REFERENCES org_types (org_type_id);
