DROP TABLE IF EXISTS agencies;
DROP TABLE IF EXISTS modes;
DROP TABLE IF EXISTS org_types;
DROP TABLE IF EXISTS types_of_service;

CREATE TABLE agencies
(
    agency_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency    TEXT NOT NULL,
    city      TEXT,
    state     TEXT
);

INSERT INTO agencies (agency_id, agency, city, state)
SELECT DISTINCT "NTD ID"   AS agency_id,
                "Agency"   AS name,
                "HQ City"  AS city,
                "HQ State" AS state
FROM public_transit_master;



CREATE TABLE modes
(
    mode_id   CHAR(1) PRIMARY KEY,
    mode_name VARCHAR(8),
    mode_desc TEXT
);

INSERT INTO modes (mode_id, mode_name)
SELECT DISTINCT SUBSTRING("3 Mode", 1, 1) AS mode_id, "3 Mode" AS mode_name
FROM public_transit_master
WHERE "3 Mode" IS NOT NULL
  AND SUBSTRING("3 Mode"
          , 1, 1) <> ''
ON CONFLICT(mode_id) DO NOTHING;

UPDATE modes
SET mode_desc = ' includes only Ferryboat mode'
WHERE mode_id LIKE 'F';

UPDATE modes
SET mode_desc = 'includes all modes that run along rails, as well as Aerial Tramway'
WHERE mode_id LIKE 'R';

UPDATE modes
SET mode_desc = 'all surface transportation modes, including Demand Response mode'
WHERE mode_id like 'B';

CREATE TABLE org_types
(
    org_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_type    TEXT NOT NULL UNIQUE
);

INSERT INTO org_types (org_type)
SELECT DISTINCT "Organization Type"
FROM public_transit_master
WHERE "Organization Type" IS NOT NULL
ON CONFLICT (org_type) DO NOTHING;

ALTER TABLE agencies
    ADD COLUMN IF NOT EXISTS org_type_id INT;

WITH raw_map AS (SELECT m."NTD ID"::integer                                    AS agency_id,
                        t.org_type_id,
                        COUNT(*) OVER (PARTITION BY m."NTD ID", t.org_type_id) AS freq
                 FROM public_transit_master m
                          JOIN org_types t
                               ON t.org_type = m."Organization Type" -- map text in master to canonical org type
                 WHERE m."NTD ID" IS NOT NULL),
     choice AS (
         -- pick the most frequent org_type per agency (tie-breaker: latest report_date if present)
         SELECT DISTINCT ON (agency_id) agency_id,
                                        org_type_id
         FROM raw_map
         ORDER BY agency_id, freq DESC)
UPDATE agencies a
SET org_type_id = c.org_type_id
FROM choice c
WHERE a.agency_id = c.agency_id;

ALTER TABLE agencies
    ADD CONSTRAINT agencies_org_type_id_fkey
        FOREIGN KEY (org_type_id) REFERENCES org_types (org_type_id);

CREATE TABLE types_of_service
(
    tos_id   TEXT PRIMARY KEY,
    tos_name TEXT
);

INSERT INTO types_of_service (tos_id)
SELECT DISTINCT public_transit_master."TOS"
FROM public_transit_master
WHERE "TOS" IS NOT NULL
ON CONFLICT (tos_id) DO NOTHING;

UPDATE types_of_service
SET tos_name = 'Directly Operated (DO)'
WHERE tos_id LIKE '%DO';

UPDATE types_of_service
SET tos_name = 'Purchased Transportation — General (PT)'
WHERE tos_id LIKE '%PT';

UPDATE types_of_service
SET tos_name = 'Purchased Transportation – Taxi (TX)'
WHERE tos_id LIKE '%TX';

UPDATE types_of_service
SET tos_name = 'Purchased Transportation — Transportation Network Company (TN)'
WHERE tos_id LIKE '%TN';
